algorithms_test: workaround missing podio dependency in JANA2
    /usr/bin/ld: /usr/local/lib/libJANA.so: undefined reference to `podio::ROOTFrameWriter::ROOTFrameWriter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    /usr/bin/ld: /usr/local/lib/libJANA.so: undefined reference to `podio::ROOTFrameWriter::finish()'
    /usr/bin/ld: /usr/local/lib/libJANA.so: undefined reference to `podio::ROOTFrameWriter::writeFrame(podio::Frame const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'