services/rootfile: add missing dependency on log_library
ld: CMakeFiles/rootfile_plugin.dir/rootfile.cc.o: in function `RootFile_service::acquire_services(JServiceLocator*)':
rootfile.cc:(.text._ZN16RootFile_service16acquire_servicesEP15JServiceLocator[_ZN16RootFile_service16acquire_servicesEP15JServiceLocator]+0x227): undefined reference to `Log_service::logger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status