algorithms/tracking: add missing dependency on EG
ld: CMakeFiles/algorithms_tracking_plugin.dir/TrackParamTruthInit.cc.o: in function `eicrecon::TrackParamTruthInit::init(std::shared_ptr<spdlog::logger> const&)':
TrackParamTruthInit.cc:(.text+0x11d): undefined reference to `TDatabasePDG::TDatabasePDG()'
ld: CMakeFiles/algorithms_tracking_plugin.dir/TrackParamTruthInit.cc.o: in function `eicrecon::TrackParamTruthInit::produce(edm4hep::MCParticle const*)':
TrackParamTruthInit.cc:(.text+0xb97): undefined reference to `TDatabasePDG::GetParticle(int) const'
ld: CMakeFiles/algorithms_tracking_plugin.dir/TruthTrackSeeding.cc.o: in function `eicrecon::TruthTrackSeeding::produce(edm4hep::MCParticle const*)':
TruthTrackSeeding.cc:(.text+0x100): undefined reference to `TDatabasePDG::GetParticle(int) const'
ld: CMakeFiles/algorithms_tracking_plugin.dir/TruthTrackSeeding.cc.o: in function `eicrecon::TruthTrackSeeding::init()':
TruthTrackSeeding.cc:(.text+0x2a9): undefined reference to `TDatabasePDG::TDatabasePDG()'
collect2: error: ld returned 1 exit status