services/geometry/acts: add missing dependencies
Fixes a linker error for `--no-undefined`:

```
ld: CMakeFiles/acts_plugin.dir/ACTSGeo_service.cc.o: in function `ACTSGeo_service::acquire_services(JServiceLocator*)':
ACTSGeo_service.cc:(.text+0x923): undefined reference to `Log_service::logger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ld: ACTSGeo_service.cc:(.text+0xb3c): undefined reference to `Log_service::logger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ld: ACTSGeo_service.cc:(.text+0xe91): undefined reference to `typeinfo for JDD4hep_service'
ld: ACTSGeo_service.cc:(.text+0xfc3): undefined reference to `JDD4hep_service::detector()'
collect2: error: ld returned 1 exit status
```