fix: convert IrtInterface to algorithm interface
This resolves conflict and brings this algorithm in compliance with the
interface.

In file included from /home/runner/work/EICrecon/EICrecon/src/algorithms/pid/IrtInterfaceJsonParser.cc:7:
/home/runner/work/EICrecon/EICrecon/src/algorithms/pid/IrtInterface.h:77:8: error: 'eicrecon::IrtInterface::init' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
   77 |   void init(DD4hep_service& service, IrtConfig& config, std::shared_ptr<spdlog::logger>& logger);
      |        ^
/opt/local/include/algorithms/algorithm.h:87:16: note: hidden overloaded virtual function 'algorithms::Algorithm<algorithms::Input<edm4hep::MCParticleCollection, edm4eic::TrackCollection, edm4eic::MCRecoTrackParticleAssociationCollection, edm4eic::TrackSegmentCollection, edm4hep::SimTrackerHitCollection>, algorithms::Output<edm4eic::IrtRadiatorInfoCollection, edm4eic::IrtParticleCollection>>::init' declared here: different number of parameters (0 vs 3)
   87 |   virtual void init() {}
      |                ^
1 error generated.