remove unused vars
```
/home/runner/work/EICrecon/EICrecon/src/algorithms/reco/FarForwardLambdaReconstruction.cc: In instantiation of 'eicrecon::FarForwardLambdaReconstruction::process(const algorithms::Algorithm<algorithms::Input<const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection>, algorithms::Output<edm4eic::ReconstructedParticleCollection, edm4eic::ReconstructedParticleCollection> >::Input&, const algorithms::Algorithm<algorithms::Input<const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection, const edm4eic::ReconstructedParticleCollection>, algorithms::Output<edm4eic::ReconstructedParticleCollection, edm4eic::ReconstructedParticleCollection> >::Output&) const::<lambda(const auto:47&, int)> [with auto:47 = std::vector<edm4eic::ReconstructedParticle>]':
/home/runner/work/EICrecon/EICrecon/src/algorithms/reco/FarForwardLambdaReconstruction.cc:355:17:   required from here
  355 |     try_neutrons(neutrons_zdc, 0);
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/runner/work/EICrecon/EICrecon/src/algorithms/reco/FarForwardLambdaReconstruction.cc:345:22: error: unused variable 'px' [-Werror=unused-variable]
  345 |         const double px = pn.x + pg1.x + pg2.x;
      |                      ^~
/home/runner/work/EICrecon/EICrecon/src/algorithms/reco/FarForwardLambdaReconstruction.cc:346:22: error: unused variable 'py' [-Werror=unused-variable]
  346 |         const double py = pn.y + pg1.y + pg2.y;
      |                      ^~
cc1plus: all warnings being treated as errors

```