CalorimeterHitReco, RomanPotsReconstruction_factory: fix UBSAN error regarding converting -1 to size_t (#677)
This is needed to facilitate #514

src/algorithms/calorimetry/CalorimeterHitReco.h:80:23: runtime error:
implicit conversion from type 'int' of value -1 (32-bit, signed) to type
'size_t' (aka 'unsigned long') changed the value to 18446744073709551615
(64-bit, unsigned)
src/detectors/RPOTS/RomanPotsReconstruction_factory.h:68:22: runtime
error: implicit conversion from type 'int' of value -1 (32-bit, signed)
to type 'size_t' (aka 'unsigned long') changed the value to
18446744073709551615 (64-bit, unsigned)