Remove unused variables Xip and Yip
Fix build on CI (it treats warnings as errors):
```
/home/runner/work/EICrecon/EICrecon/src/algorithms/fardetectors/PolynomialMatrixReconstruction.cc: In member function 'virtual void eicrecon::PolynomialMatrixReconstruction::process(const algorithms::Algorithm<algorithms::Input<edm4hep::MCParticleCollection, edm4eic::TrackerHitCollection>, algorithms::Output<edm4eic::ReconstructedParticleCollection> >::Input&, const algorithms::Algorithm<algorithms::Input<edm4hep::MCParticleCollection, edm4eic::TrackerHitCollection>, algorithms::Output<edm4eic::ReconstructedParticleCollection> >::Output&) const':
/home/runner/work/EICrecon/EICrecon/src/algorithms/fardetectors/PolynomialMatrixReconstruction.cc:234:12: error: unused variable 'Xip' [-Werror=unused-variable]
  234 |     double Xip[2] = {0.0, 0.0};
      |            ^~~
/home/runner/work/EICrecon/EICrecon/src/algorithms/fardetectors/PolynomialMatrixReconstruction.cc:236:12: error: unused variable 'Yip' [-Werror=unused-variable]
  236 |     double Yip[2] = {0.0, 0.0};
      |            ^~~
cc1plus: all warnings being treated as errors
```