rm unused function
```
/home/runner/work/EICrecon/EICrecon/src/algorithms/reco/FarForwardLambdaReconstruction.cc:24:20: error: unused function 'toTVector3' [-Werror,-Wunused-function]
   24 | static inline void toTVector3(TVector3& v1, const edm4hep::Vector3f& v2) {
      |                    ^~~~~~~~~~
1 error generated.
```