linux-eic-shell: update llvm-cov from 15 to 18 (#1983)
eic-shell now ships with llvm/clang 18, so we started running into:
```
warning: src/tests/algorithms_test/algorithms_test.profraw: unsupported instrumentation profile format version
error: no profile can be merged
```