utilities/dump_flags: fix compilation with C++17
The `std::ptr_fun` was deprecated since C++11 and removed in C++17

```
src/utilities/dump_flags/DumpFlags_processor.h:83:84: error: no member named 'ptr_fun' in namespace 'std'
        std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), std::ptr_fun<int, int>(std::tolower));
                                                                              ~~~~~^
```