TrackPropagation_factory: HcalBarrel_ID -> HCalBarrel_ID (#1070)
Fixes: 6bef773f ('feat: add system and layer ID to Acts::Surface
GeometryIdentifier')


https://github.com/eic/EICrecon/actions/runs/6478157904/job/17589778133?pr=1069#step:5:605

> Error: [JEventProcessorPODIO] [error] Omitting PODIO collection
'CalorimeterTrackProjections' due to exception: getRefChild: Failed to
find child with name: HcalBarrel_ID Map contains 1759 elements: ...