jana_plugin.cmake: explicitly depend plugins on podio_datamodel_glue (#1772)
### Briefly, what does this PR introduce?

https://github.com/eic/EICrecon/pull/1704 broke multiprocess builds
(e.g. `make -j10`). The issue is that cmake header scanner ignores rule
that generates datamodel_glue.h, which leads to race conditions:
```
src/services/io/podio/JEventSourcePODIO.cc:30:10: fatal error: services/io/podio/datamodel_glue.h: No such file or directory
   30 | #include "services/io/podio/datamodel_glue.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This PR introduces a target-level dependency. The case of external
plugin is handled by the fact that the headers are installed along with
EICrecon.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users
need to make to their code?
No

### Does this PR change default behavior?
No